#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"

if [[ -L $SOURCE ]]
then
    DIR=$(php -r "echo dirname(realpath('$SOURCE'));")
else
    DIR="$( cd "$( dirname "$SOURCE" )" && pwd )"
fi

if [ ! -f "$DIR/cli/marquis.php" ]
then
    DIR=$(php -r "echo realpath('$DIR/../elder/marquis');")
fi

if [[ "$EUID" -ne 0 ]]
then
    sudo $SOURCE "$@"
    exit
fi


php "$DIR/cli/marquis.php" "$@"
